config/crd/bases/kubeadm.bootstrap.cluster.sigs.k8s.io_kubeadmbootstrapconfigs.yaml, kubeadm/v1beta1/bootstraptokenstring.go, kubeadm/v1beta2/bootstraptokenstring.go
This PR fixes the json tags in the bootstrap token. They should be ignored by json.Marshal and use the custom Unmarshal/Marshal functions instead.
Please see https://github.com/kubernetes/kubernetes/pull/80050
```release-note
NONE
```
=> Fix json tags on kubeadm types

Makefile, go.sum, main.go
* Remove dependency on kustomize (use kubectl kustomize instead)
This PR implements main straight out of Kubebuilder book except for our types.
This removes the dependency on kustomize when installing the manager and instead uses `kubectl kustomize`.
```release-note
NONE
```
/assign @fabriziopandini 
/cc @amy @neolit123 @vincepri
=> Implement main.go

hack/verify-all.sh
This PR makes the output of hack/verify-all.sh more useful by only showing the output of the failed files.
Related to #35 
```release-note
NONE
```
/assign @neolit123 
<details><summary>The output</summary>
```
chuckh-a02:cluster-api-bootstrap-provider-kubeadm cha$ ./hack/verify-all.sh 
[*] Verifying whitespace...
[*] Verifying spelling...
[*] Verifying boilerplate...
[*] Verifying gofmt...
[*] Verifying golint...
[*] Verifying govet...
[*] Verifying deps...
[*] Verifying gotest...
[*] Verifying build...
Some of the verify scripts failed:
- verify-boilerplate.sh:
skipping ".github/ISSUE_TEMPLATE/bug_report.md": unsupported file type
skipping ".github/ISSUE_TEMPLATE/feature_request.md": unsupported file …
```
=> only print failed verfiy outputs

api/v1alpha1/kubeadmbootstrapconfig_types.go, config/crd/bases/kubeadm.bootstrap.cluster.sigs.k8s.io_kubeadmbootstrapconfigs.yaml, go.mod
This PR uses the new Ready bool field instead of the old Phase enum/string field.
/cc @amy 
/assign @vincepri 
Fixes #37 
There was a go.mod change that snuck in as well. I can pull it out if there are concerns. It is related to #31 
```release-note
NONE
```
=> Use a ready/bool instead of phase

controllers/certificates.go, controllers/certificates_test.go
This PR pulls in code to generate certificates. It is unused. I may have to pull in additional code from CAPA but I will do so as it is necessary.
A bunch of stuff has been cleaned up from CAPA which is why you will see differences.
Related to #16 
```release-note
NONE
```
=> Adds certificate generation code pulled from capa

config/default/kustomization.yaml
This patch fixes deprecated and invalid YAML in the kustomize.yaml file.
Patches got replaced. Please see: https://github.com/kubernetes-sigs/kubebuilder/pull/872
=> Fix for kustomize v3.0

main.go
This PR allows the manager to work with with the default `--enable-leader-election` flag that kubebuilder has added to the Deployment YAML.
```release-note
Enable highly available manager
```
=> Enable leader election in manager

Makefile
Changes the default GOPROXY to use existing environment variables
Fixes #64
=> Enable GOPROXY default in Makefile

controllers/kubeadmconfig_controller.go, controllers/kubeadmconfig_controller_reconciler_test.go
This uses the infrastructureReady bool on the status instead of the Annotation. It may not be in the right spot, but @fabriziopandini is working on that.
```release-note
NONE
```
/assign @fabianofranz @ncdc
=> Fix infrastructure ready

Dockerfile, config/manager/manager.yaml
This PR allows the container to restart properly. The yaml was overriding the container ENTRYPOINT which I did not want to have happen.
I'm not sure if this is best practice or if I should rewrite the command in the yaml or what. This seemed as good an option as any so I went with it. 
If you have strong opinions or Know About This please leave a comment
```release-note
NONE
```
=> Fix up image restart process

controllers/control_plane_init_locker.go, controllers/control_plane_init_locker_test.go
As discussed in https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/82, the control plane init locker is required in order to ensure only a KubeadmConfig/Machine in the cluster is configured as a init node. 
NB. This is a safeguard that prevents errors in case more that one KubeadmConfig/Machine is configured with ClusterConfiguration/InitConfiguration
/assign @chuckha
=> Restore control plane init locker

cloudinit/controlplane_join.go, controllers/kubeadmconfig_controller.go, controllers/kubeadmconfig_controller_reconciler_test.go, controllers/kubeadmconfig_controller_test.go
@ncdc @chuckha 
disclaimer: I'm still in learning mode.
This PR is an attempt to get the reconciler loop properly manage the creation of the init control plane. Main points I want to discuss with you:
1. While `cluster.x-k8s.io/infrastructure-ready` is not set, everything should wait
1. If `cluster.x-k8s.io/infrastructure-ready==true`, while `cluster.x-k8s.io/control-plane-ready` is not set
1. we should ensure only one config/one machine is set for acting as init control plane; this requires the init-lock mechanism to be in place
2. everything else should wait
1. if `cluster.x-k8s.io/infrastructure-ready==true` and `cluster.x-k8s.io/control-plane-ready==true the reconciler loop should handle join control plane and join workers
=> Reconciler loop

controllers/kubeadmconfig_controller.go
This PR wires up AdditionalUserDataFiles to generation code
Fixes #90 
```release-note
```
=> use AdditionalUserDataFiles in bootstrap data generation

Makefile
This is necessary since `go env GOPROXY` will return an empty string if the value is not set, thus setting GOPROXY to an empty string, which doesn't quite do what we want.
I've verified this locally by doing a fresh checkout without `GOPROXY` being set and running `make test`, which resulted in:
```
verifying gomodules.xyz/jsonpatch/v2@v2.0.0: checksum mismatch
downloaded: h1:OyHbl+7IOECpPKfVK42oFr6N7+Y2dR+Jsb/IiDV3hOo=
go.sum:     h1:lHNQverf0+Gm1TbSbVIDWVXOhZ2FpZopxRqpr2uIjs4=
make: *** [fmt] Error 1
```
After applying this change and running `make test` again things worked as expected.
```release-note
NONE
```
/cc @chuckha @amy
=> Set GOPROXY to default if it is not configured

controllers/control_plane_init_locker_test.go, controllers/kubeadmconfig_controller.go, controllers/kubeadmconfig_controller_test.go, go.mod, go.sum
This PR uses the util code and removes some boilerplate making the Reconcile function shorter and easier to read.
It also bumps CAPI version and refactors some test logic.
```release-note
NONE
```
=> Use CAPI utils to reduce boilerplate

controllers/kubeadmconfig_controller.go, go.sum, kubeadm/v1beta1/groupversion_info.go, kubeadm/v1beta1/utils.go
Currently, the userdata has the kubeadm config structs as json, which kubeadm doesn't seem to like.
Sample from a provisioned host:
```
---
{"nodeRegistration":{"kubeletExtraArgs":{"cni-bin-dir":"/opt/cni/bin","cni-conf-dir":"/etc/cni/net.d","network-plugin":"cni","node-ip":"<redacted>"}},"localAPIEndpoint":{"advertiseAddress":"","bindPort":0}}
```
To avoid importing k/k I grabbed a utility function and copied it here, MarshalToYamlForCodecs.
```release-note
```
=> chore: get kubeadm yaml rather than json

Makefile
Remove unused boilerplate.go.txt. 
`boilerplate.go.txt` is now in `hack/boilerplate/boilerplate.go.txt`
Fixes #
```release-note
NONE
```
=> Update Makefile that runs generates to use the generate boilerplate instead of the go boilerplate

config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml
This PR is one solution to #129. It may not be optimal but does at least work.
Fixes #129
If this args is added to the manager_image_patch then there is a patch merge conflict.
```release-note
NONE
```
=> Set the args in the manager_auth_proxy_patch.yaml

controllers/kubeadmconfig_controller.go
This PR cleans up some misleading logs and provides a nicer experience when a machine might be a control plane machine.
/assign @fabriziopandini @detiber 
```release-note
NONE
```
=> Clean up some misleading logs

controllers/control_plane_init_locker.go, controllers/control_plane_init_locker_test.go, controllers/kubeadmconfig_controller.go
This PR prevents the bootstrapper to run kubeadm init on two nodes
Fixes #99 
```release-note
```
/assign @chuckha 
/assign @fabriziopandini
=> Only one node should do kubeadm init

controllers/kubeadmconfig_controller.go
Previously we were attempting to retrieve the kubeconfig secret using ClusterConfiguration.ClusterName, but we weren't ensuring that the value defaulted to the name of the linked Cluster.
```release-note
NONE
```
=> Handle setting of ClusterConfiguration.ClusterName

config/rbac/role.yaml, controllers/control_plane_init_locker.go, controllers/kubeadmconfig_controller.go
bootstrap provider creates the lock, but can't delete or release it because its looking in the wrong namespace and lacks perms. 
Fixes #
```release-note
- release lock from correct namespace update rbac accordingly 
```
=> chore: release lock from correct namespace

certs/certs.go
allows for time skew in pivot cluster workflow
Fixes #158 
```release-note
Adjust NotBefore on certificate generation to allow slight time skew.
```
=> allow for time skew in cert generation

Dockerfile.dev
This PR renames the current `Dockerfile` into `Dockerfile.dev` and adds a production-ready  `Dockerfile` ("kubebuilder2" bases + GOPROXY + USER nobody) 
```release-note
NONE
```
/assign @vincepri @chuckha
=> production ready dockerfile

Makefile
This makes it easier to figure out what commands are available via make without having to read through the Makefile. Implemented using the changes from kubernetes-sigs/cluster-api#631.
```shell
$ make help
Usage:
make <target>
help                  Display this help
test                  Run tests
manager               Build manager binary
run                   Run against the configured Kubernetes cluster in ~/.kube/config
install               Install CRDs into a cluster
deploy                Deploy controller in the configured Kubernetes cluster in ~/.kube/config
fmt                   Run go fmt against code
vet                   Run go vet against code
generate              Generate code
generate-deepcopy     Generate deepcopy files. …
```
=> Add 'help' target to Makefile and make it the default

api/v1alpha2/kubeadmconfigtemplate_types.go, config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
Adds the cluster-api group to the KubeadmConfigTemplate type
=> :sparkles: Add cluster-api group to KubeadmConfigTemplate

main.go
This makes the [Manager SyncPeriod](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#Options.SyncPeriod) configurable via a command-line flag and defaults it to 10 minutes instead of 10 hours.
Fixes #175
=> ✨ Make Manager SyncPeriod configurable via flag

api/v1alpha2/kubeadmbootstrapconfig_types.go, cloudinit/cloudinit_test.go, cloudinit/files.go, cloudinit/utils.go, config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml, config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
This PR adds an Encoding type for the cloud init files.
Related to #202 
/assign @detiber
=> :warning: Adds encoding field for cloud-init files

.golangci.yml
Fixes a typo in the golint-ci config file and adds an exclude to ignore shadowing in test cases.
=> 🐛 Fix golangci-lint config to ignore unhelpful lints

controllers/kubeadmconfig_controller.go, controllers/kubeadmconfig_controller_test.go
What this PR does / why we need it:
Removes error and waits again if
a) machine does not have any associated cluster
b) Machine has associate cluster but it is still non-existent
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #212
=> :bug: Fix error-return for machine-cluster association

main.go
Adds support to restrict the controller manager to just reconciling a single namespace instead of all namespaces
Fixes #228
=> :sparkles: Allow restricting namespace for the controller manager

controllers/kubeadmconfig_controller.go
Signed-off-by: JunLi <lijun.git@gmail.com>
There is no need to update KubeadmConfig objects if any error occurs during the reconciliation.
=> Patch kubeadmconfig objects only if no error occurs during reconciliation

controllers/kubeadmconfig_controller_test.go
This PR adds a test case  - Return early if the owning machine does not have an associated cluster.
**Which issue(s) this PR fixes**  :
Ref #214
=> 🏃Added Test :Return early if the owning machine does not have an associated cluster

cloudinit/cloudinit_test.go, cloudinit/controlplane_init.go, cloudinit/controlplane_join.go, controllers/kubeadmconfig_controller.go, controllers/kubeadmconfig_controller_test.go, docs/external-etcd.md, internal/cluster/certificates.go, internal/cluster/certificates_test.go
This PR adds additional support + documentation for creating kubernetes clusters that use external etcd.
cc @rbankston
Fixes #59
Fixes #255
=> ✨ Adds support for external etcd & respects custom certificates directory from kubeadm

controllers/kubeadmconfig_controller.go, controllers/kubeadmconfig_controller_test.go, internal/cluster/certificates.go, internal/cluster/certificates_test.go
With the introduction of support for external etcd comes better
certificate management. This commit separates the worker join certificate
logic from the control plane join certificate logic.
This PR fixes the bug where control-planes could not join a cluster but were still provisioned.
Fixes #262 
/cc @vincepri
=> 🐛 Separate certificate logic for joins

controllers/kubeadmconfig_controller.go, controllers/kubeadmconfig_controller_test.go, controllers/token.go, main.go
Refreshes the token for a machine that's not used it. 
Fixes #248
=> 🐛 Refresh token for provisioning machines

controllers/kubeadmconfig_controller.go, controllers/kubeadmconfig_controller_test.go
For init configurations or non-BootstrapToken discovery mechanisms, we
shouldn't be trying to refresh tokens.
Fixes a panic reconciling kubeadm configs for a control plane init before the control plane is marked as "ready"
Fixes #266
=> fix: ensure there's a token to refresh

config/manager/manager.yaml
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>
Adds toleration for well-known taints like `node-role.kubernetes.io/master` to released CABPK manager manifest.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/1486
=> add well-known tolerations to released CABPK components

cloudinit/cloudinit_test.go, cloudinit/commands.go
Removes the commands single quote and formats it with `%q`
**Which issue(s) this PR fixes** :
Fixes #192
=>  🐛 Fixes an issue where KubeadmConfig Pre/PostKubeadmCommands were not being properly escaped 

internal/locking/control_plane_init_mutex.go
fix unmarshal err for blank field
```
E1021 16:37:15.521443       1 control_plane_init_mutex.go:67] init-locker "msg"="Failed to get information about the existing lock" "error"="failed to unmarshal semaphore information: unexpected end of JSON input" "cluster-name"="capi-quickstart" "configmap-name"="capi-quickstart-lock" "namespace"="default"
```
Fixes #
=> fix unmarshal err for blank field

Makefile, docs/release.md
test-infra has been updated to use GCB to build release version images,
so we no longer need to do it here in the repo.
Requires https://github.com/kubernetes/test-infra/pull/15624
Fixes #
=> 🏃 Let GCB build release images

.gitignore, config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml, config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml, kubeadm/v1beta1/types.go
Fixes a long standing issue that was causing pain and fear 😂 
/assign @chuckha @ncdc
=> ⚠️ ClusterConfigration.Networking.* fields are now optional

.golangci.yml, main.go
Following up on this [PR](https://github.com/kubernetes-sigs/cluster-api/pull/2084). Adding `pprof` to this repo.
=> ✨ import and enable pprof

api/v1alpha2/kubeadmbootstrapconfig_types.go
- add `omitempty` to the `passwd` field since its optional 
Fixes #291
=> 🐛 passwd field is omitempty because it's optional

controllers/kubeadmconfig_controller_test.go
As per the Kubernetes effort to remove offensive words from the codebase.
**Which issue(s) this PR fixes**:
Rif https://github.com/kubernetes-sigs/cluster-api/issues/3282
/assign @vincepri
=> 🏃 Remove offensive words from the codebase
