kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm

- .gitignore
- Dockerfile
- Makefile
- PROJECT
- config/certmanager/certificate.yaml
- config/certmanager/kustomization.yaml
- config/certmanager/kustomizeconfig.yaml
- config/default/kustomization.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_image_patch.yaml
- config/default/manager_prometheus_metrics_patch.yaml
- config/default/manager_webhook_patch.yaml
- config/default/webhookcainjection_patch.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- config/rbac/auth_proxy_role.yaml
- config/rbac/auth_proxy_role_binding.yaml
- config/rbac/auth_proxy_service.yaml
- config/rbac/kustomization.yaml
- config/rbac/leader_election_role.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/role_binding.yaml
- config/webhook/kustomization.yaml
- config/webhook/kustomizeconfig.yaml
- config/webhook/service.yaml
- hack/boilerplate.go.txt
- hack/install-controller-runtime.sh
- hack/verify-all.sh
- hack/verify-gofmt.sh
- hack/verify-golint.sh
Trying just the first part of the initial commit. Haven't incorporated feedback from #3 yet.
> Init the kubebuilder project

- hack/verify-all.sh
> Fix verify-all

- Dockerfile
- Makefile
- config/crd/bases/kubeadm.bootstrap.cluster.sigs.k8s.io_kubeadmbootstrapconfigs.yaml
- config/default/kustomization.yaml
- config/manager/manager.yaml
- config/rbac/role.yaml
- controllers/kubeadmbootstrapconfig_controller.go
- controllers/suite_test.go
- kubeadm/v1beta1/bootstraptokenstring.go
- kubeadm/v1beta2/bootstraptokenstring.go
This PR adds scaffolding and some fixes to make testing a little bit nicer
The code doesn't do anything very special, I'm not even sure if it's right
```release-note
None
```
> Adds some manager code that does nothing

- cloudinit/cloudinit.go
- cloudinit/controlplane_certs.go
Fix the linter that somehow is broken
Please make sure the tests pass
```release-note
NONE
```
> Fix the linter

- controllers/control_plane_init_locker.go
- controllers/control_plane_init_locker_test.go
Move control plane locker from CAPA
Fixes #29
```release-note
NONE
```
> Move control plane locker from CAPA

- hack/verify-all.sh
This checks for error codes that are not just 1.
Related to  #35 
```release-note
NONE
```
/assign @ashish-amarnath
> fix bug in verify-all script

- Makefile
Use PHONY in Makefile
Fixes #
```release-note
NONE
```
> Use PHONY in Makefile

- controllers/kubeadmconfig_controller_reconciler_test.go
- controllers/kubeadmconfig_controller_test.go
- hack/verify-gofmt.sh
FOUND! Thanks @ncdc for reporting this one. This has been bugging me for a while.
@neolit123 might want to be aware of this one and see if it exists elsewhere.
Fixes #70
After this first push I am going to have to actually fix the tests here as well.
/assign @ncdc 
```release-note
NONE
```
> Fix verify-gofmt

- Makefile
Fixes #71
```release-note
NONE
```
> Always use the right controller-gen

- controllers/kubeadmconfig_controller.go
Fixes #63 
```release-note
NONE
```
> Switch from Update() to Patch()

- Makefile
- hack/verify-all.sh
- hack/verify-manifests.sh
- Adds verify manifests script
Fixes #73
> Verify manifests script

- cloudinit/controlplane_init.go
- cloudinit/controlplane_join.go
- cloudinit/node.go
- controllers/kubeadmconfig_controller.go
- controllers/kubeadmconfig_controller_reconciler_test.go
- controllers/kubeadmconfig_controller_test.go
This PR allows the controller to match Refs with  machines properly.
Fixes #80 
```release-note
NONE
```
> Fix machine ref matching

- hack/verify-all.sh
- hack/verify-docker-build.sh
Fixes #86 
```release-note
```
> chore: add verify-docker-build.sh

- controllers/kubeadmconfig_controller.go
Refactor the controller to only use Patch to update a config. Don't use update.
Fixes #94
```release-note
NONE
```
> Refactor: use Patch instead of Update to update a config

- controllers/kubeadmconfig_controller.go
Just in case anyone else is also unfamiliar with named refs: https://play.golang.org/p/lYK6-yqssqs
This PR will allow us to not think about when we should call patch and simply always patch the objects while still returning the correct result and error.
```release-note
NONE
```
/assign @detiber @fabianofranz
> Defer the patch

- main.go
Initializes logger flags like `-logtostderr` and `-v`.
Fixes #113 
Do we want to change any of the defaults?
```release-note
initialize logger flags
```
/cc @chuckha
> chore: initialize klog flags

- api/v1alpha2/suite_test.go
- controllers/control_plane_init_locker_test.go
- controllers/kubeadmconfig_controller_reconciler_test.go
- controllers/kubeadmconfig_controller_test.go
- controllers/suite_test.go
This PR switches any logger to use `klog/klogr` in any parts of the codebase to provide consistency between tests and runtime.
Fixes #
```release-note
```
> Use same logger throughout the codebase

- api/v1alpha2/kubeadmbootstrapconfig_types.go
- config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
This PR adds kubebuilder directives to `KubeadmConfig` to ensure:
- Object is namespaced.
- Object has a `Status` subresource.
- The current version is marked as stored version.
Fixes #
```release-note
```
> Add kubebuilder markers to CRDs for status and namespace

- config-capi/manager/manager.yaml
- config/manager/manager.yaml
- config/rbac/auth_proxy_service.yaml
- config/webhook/service.yaml
Update `control-plane` label value as `cabpk-controller-manager`.
`controller-manager` can't tell what kind of controller manager it is, I think.
Fixes #
I found that the label `kube-controller-manager` uses is `component=kube-controller-manager`.
We can also consider adding a `component=cabpk-controller-manager` label.
```release-note
NONE
```
/cc @chuckha @ncdc
> Update control-plane label value as cabpk-controller-manager

- Makefile
- hack/verify-manifests.sh
This PR aligns this Makefile with the other Cluster API repositories, where `make generate` runs a bunch of `*-generate` targets.
Fixes #
```release-note
```
> Streamline make generate

- controllers/kubeadmconfig_controller.go
Now that we're using [controller-runtime@v0.2.0-beta.5](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.2.0-beta.5), this hack can be removed.
Fixes #
```release-note
```
> Remove gvk hack from deferred patch

- certs/certs.go
- certs/utils.go
- controllers/kubeadmconfig_controller.go
Fixes #114 
```release-note
- kubeconfig as a secret
```
> chore: kubeconfig as secret

- config/rbac/role.yaml
- controllers/kubeadmconfig_controller.go
Fixes #132
```release-note
NONE
```
> Fix manager rbac permission

- config/rbac/role.yaml
- controllers/kubeadmconfig_controller.go
The init locker needs access to do configmap things, so we must allow this.
Fixes #
```release-note
```
> chore: add rbac for configmaps

- api/v1alpha2/kubeadmbootstrapconfig_types.go
- api/v1alpha2/zz_generated.deepcopy.go
- cloudinit/cloudinit.go
- cloudinit/controlplane_init.go
- cloudinit/controlplane_join.go
- cloudinit/node.go
- config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
- controllers/kubeadmconfig_controller.go
This PR adds `AdditionalCommands` to Kubeadm spec and wires it up in the reconciler
Fixes #108 
```release-note
```
/cc @chuckha
> AdditionalCommands support in kubeadm spec

- controllers/kubeadmconfig_controller.go
- controllers/kubeadmconfig_controller_test.go
A user now has several places to define some settings. One the cluster/machine object and one on the kubeadm config object. 
**Which issue(s) this PR fixes**:
Fixes # https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/78
This PR handle conflicts in the same ways CABPK is already handling similar situations for bootstrap tokens, certificates, controlplaneEnpoint:
- If a value is defined in the KubeadmConfig, such value is respected, otherwise, values from topmost level objects are used and the override is tracked in logs.
```release-note
NONE
```
/assign @detiber @chuckha
> Reconcile top most level objects

- config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
- kubeadm/v1beta1/types.go
My team noticed this when applying some yaml during node creation. Is the v1beta2 stuff used yet? 
Fixes #
```release-note
```
> chore: add omitempty to fields

- api/v1alpha2/kubeadmbootstrapconfig_types.go
- config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
Add capi categories so that we can do `kubectl get cluster-api`
Fixes #
```release-note
```
> add capi categories

- config/crd/kustomization.yaml
Running `kustomize build "github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm//config/default/?ref=master"` fails with error `2019/08/20 10:31:27 invalid patches from <nil>`, this fixes the error and allows for files to be properly generated.
Fixes #
```release-note
```
> :bug: Comment out empty patches

- api/v1alpha2/kubeadmbootstrapconfig_types.go
- config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
- config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
- hack/verify-manifests.sh
This PR adds the field `Format` to `KubeadmConfig.Spec`. 
The `Format` is a required field that specifies the output format of the bootstrap data.
Fixes #121 
The `Format` field needs to be wired up. An issue will be opened to discuss how to use the field in the controller.
```release-note
```
> Format field in KubeadmConfig.Spec

- config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
- config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
- kubeadm/v1beta1/types.go
This PR is an effort to improve the UX by adding the kubebuilder `// +optional` marker to fields that are either defaulted in this provider or that can be left empty.
Related to #112 
```release-note
```
> Mark kubeadm optional fields with +optional

- cloudinit/utils.go
As part of b48ccb5d88005be73a4f49e29c8efef37074d9b4, this constant was added/moved to [`certs/files.go`](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/master/certs/files.go#L22), so it's no longer needed here.
Fixes #
```release-note
```
> Remove unused rootOwnerValue constant

- kubeadm/v1beta2/types.go
In order to appease `goimports` and follow the convention across other parts of the codebase, I decided to give this import an identifier.
Fixes #
```release-note
```
> Disambiguate v1 import

- api/v1alpha2/kubeadmbootstrapconfig_types.go
- config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
Add ErrorReason/ErrorStatus to CRD statuses so it's easier to debug. 
Fixes #97 
```release-note
```
> add ErrorReason/ErrorStatus to CRD statuses

- cloudinit/utils.go
This function was made obsolete by the changes in b48ccb5d
Fixes #
```release-note
```
> Remove unused isKeyPairValid function

- cloudinit/node.go
> fix write files for worker nodes

- Dockerfile
- Dockerfile.dev
- Makefile
- config/default/manager_image_patch.yaml
This PR adds multi-arch to this provider, as seen in CAPI and CAPA.
Fixes #
```release-note
```
> ✨ Add multi-arch docker targets support

- .github/workflows/main.yml
> ✨ Add github action to push on master merge

- README.md
This PR updates the project read me with instruction about how to test CABPK, example configs and description of the recently added features
I'm not sure if the documentation should go here, in https://cluster-api.sigs.k8s.io/, or in both...
```release-note
Improved documentation
```
/cc @chuckha @detiber @vincepri
> 📖 Update Documentation

- certs/utils.go
- controllers/kubeadmconfig_controller.go
- controllers/kubeadmconfig_controller_test.go
This PR calculates the CA hashes to be used when verifying bootstrap tokens with kubeadm
Fixes #123 
```release-note
Improves security by checking CACert hashes on kubeadm join
```
> ✨ Calculate cert hashes and verify CA certificates

- .github/workflows/main.yml
- Makefile
> :sparkles: Add tag to action, update Makefile

- config/rbac/role.yaml
- controllers/kubeadmconfig_controller.go
> 🐛 Fix a Cluster -> KubeadmConfig mapper bug

- certs/files.go
- cloudinit/cloudinit.go
- controllers/kubeadmconfig_controller_reconciler_test.go
- controllers/kubeadmconfig_controller_test.go
- controllers/suite_test.go
- controllers/token.go
Trying to keep consistency in how the imports are named across the repository.
Fixes #
> 🏃‍♂️ Name v1alpha2 imports

- controllers/kubeadmconfig_controller.go
> 🐛Fix NPE when looking at Cluster Network fields

- Dockerfile.dev
Fixes the development docker file
> 🐛 Fix development dockerfile

- certs/certs.go
- certs/utils.go
- controllers/kubeadmconfig_controller.go
> ⚠️ Remove kubeconfig generation

- Makefile
- go.mod
- go.sum
Improve makefile release process.
Bump CAPI to v0.2.0
> :running: Update Makefile

- Makefile
- main.go
Do some code cleaning :-)
Fixes #
> Do some code cleaning

- controllers/kubeadmconfig_controller.go
Add APIServerEndpoint validation for JoinConfiguration
Fixes #
> Remove redundant TODOs

- controllers/kubeadmconfig_controller.go
- controllers/kubeadmconfig_controller_reconciler_test.go
- controllers/kubeadmconfig_controller_test.go
This PR cleans up and documents the behaviors being tested as a followup from https://docs.google.com/document/d/1g6xxhD_AFA4klrm87f7o0XpEtOOZfbSIat3ltKmbvrc/edit#
> 🏃Document tests with minor clean ups

- controllers/kubeadmconfig_controller_test.go
This PR adds a test to ensure that KubeadmConfigs are reconciled when their associated clusters are modified.
Included in this PR are also a few bug fixes for the test helpers. This corrects an erroneous APIVersion (missing group) and adds the forward reference to the machine. It was only adding the backwards owner reference.
Related to #214 
/assign @fabriziopandini
> 🏃 Adds a test to reconcile kubeadmconfig based on clusters

- controllers/kubeadmconfig_controller_test.go
code clean: controlPane -> controlPlane
Fixes #
> code clean: controlPane -> controlPlane

- Makefile
Adds lint test to make test command
> :sparkles: Add lint to make test command

- controllers/kubeadmconfig_controller.go
- controllers/kubeadmconfig_controller_test.go
What this PR does / why we need it:
Corrects the mapping function used for triggering Kubeadmconfig reconcile in case Machine is modified
Fixes kubernetes-sigs#227
> :bug: Fix a Machine -> KubeadmConfig mapping bug

- controllers/kubeadmconfig_controller.go
Signed-off-by: JunLi <lijun.git@gmail.com>
Fix bug for the init lock. 
Consider the following case:
Two control plane machines(note them as C1, C2) are creating concurrently. Assume C1 first acquires the init lock. Since C2 failed to get lock, it exits the reconcile loop and releases the init lock. 
**Before C1 finished to initialize itself**, we create another control plane machine(note it as C3). Obviously, C3 will acquire the init lock successfully and also generate controlplane-init config which is what we do not want to see.
> 🐛 Fix init lock

- controllers/kubeadmconfig_controller_test.go
Add a test to ensure that exactly one control plane machine initializes if there are multiple control plane machines defined
Ref #214
> 🏃‍♂️ Add a test to ensure that exactly one control plane machine initializes if there are multiple control plane machines defined

- Makefile
Small cleanup for Makefile :)
Fixes #
> Small cleanup for Makefile

- controllers/kubeadmconfig_controller_test.go
Add test for patch behavior
Fixes #243
> 🏃 Add test for patch behavior

- OWNERS_ALIASES
@SataQiu has been an excellent reviewer and contributor to the project. I would like to promote him to a maintainer moving forward.
This will have a 1 week lazy consensus.
/hold
> 🎉 Promote @sataqiu to a maintainer

- tilt-provider.json
> :sparkles: Add tilt support

- config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
- config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
- kubeadm/v1beta1/types.go
This PR is a backport of https://github.com/kubernetes-sigs/cluster-api/pull/2678
> Mark defaulted fields as optional
